"""Init

Revision ID: 5e42e313e288
Revises: 16a49d3e8033
Create Date: 2024-01-20 00:38:47.793730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e42e313e288'
down_revision: Union[str, None] = '16a49d3e8033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product', sa.String(length=100), nullable=False))
    op.drop_constraint('products_name_key', 'products', type_='unique')
    op.create_unique_constraint(None, 'products', ['product'])
    op.drop_column('products', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='unique')
    op.create_unique_constraint('products_name_key', 'products', ['name'])
    op.drop_column('products', 'product')
    # ### end Alembic commands ###
