"""last1

Revision ID: 6ee629690dc8
Revises: fe96ab879d3c
Create Date: 2024-01-28 22:34:11.552435

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6ee629690dc8"
down_revision: Union[str, None] = "fe96ab879d3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
